### ISSUE TITLE
Merge triage csvs

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#12]
Merge image_info.csv; filesystem.csv; level1.csv into [input directory]_stabilization.csv

Match the merged data on the media number.

**Comment by dd388** [comment]
If all the scripts will eventually be chained together and run in sequence (with the output names fixed) it may be reasonable to assume this layout of csv files for the various pieces:

```
├── image_info.csv
└── organized
    ├── filesystem.csv
    └── level1.csv
```

**Comment by dd388** [comment]
Okay, just made a small change I should test. https://github.com/cul-it/rmc-workflow-scripts/commit/4c4f52978bd3c80d7525d38d40073cb88bdd9272

**Comment by dd388** [comment]
Looks OK, now all csv files to be aggregated will live in `organized`

**Comment by dd388** [comment]
There was another subtle thing I changed here with the other scripts. Instead of pointing the scripts to the organized directory explicitly, you point it to the directory above that (where you started) which will then contact a directory called "organized." https://github.com/cul-it/rmc-workflow-scripts/commit/5ba401a71dc029571c197200b41b2fe077b8f66e This was to get the naming of the stabilization csv file as specified above.

**Comment by dd388** [comment]
Minimally tested by me, needs further testing. If errors, we'll reopen.
